# 生产环境
server:
  port: 9998
spring:
  datasource:
    primary:
      url: jdbc:mysql://biaoshuking.mysql.rds.aliyuncs.com:3306/intelligence-prod?useUnicode=true&rewriteBatchedStatements=true&characterEncoding=utf-8
      username: hngp
      password: hngp123
      max-wait: 10000
      max-idle: 100
      max-active: 100
      test-while-idle: true
      test-on-borrow: true

  jpa:
    properties:
      hibernate:
        hbm2ddl:
          auto: update
        show_sql: true
        current_session_context_class: org.springframework.orm.hibernate5.SpringSessionContext
eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:11111/eureka/
